name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - base

jobs:
  ci:
    strategy:
      fail-fast: true

    name: CI (stable)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Stable
      run: |
        rustc -vV
        rustup update stable
        rustup default stable
        rustc -vV

    - name: Install valgrind
      run: |
        sudo apt-get update 
        sudo apt-get -y install valgrind

    - name: Build
      run: cargo build --verbose --all
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Run tests
      run: sudo env PATH=$PATH make check
